source: src/pages/
paths:
  uploads: uploads
collections_config:
  pages:
    path: /
    output: true
    url: '[relative_base_path]/[slug]'
    name: Pages
    description: markdown pages
    icon: notes
    _editables: {}
    _enabled_editors:
      - visual
      - content
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_enabled_editors:
  - content
  - visual
  - data
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
